config/routes.rb
Rails.application.routes.draw do
  resources :templates

  root 'templates#index'

end

app/models/template.rb
class Template < ActiveRecord::Base
	serialize :questions, JSON
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_params
      params.require(:template).permit(:name, :is_active, questions: [:question_no, :question_name, :question_type])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjhenleyQuestionSoftware</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <% if @template.persisted? %>
    <% f.object.questions.each  do |q| %>
      <div class="field">
        <%= text_field_tag :question_no, nil, value: "#{q[1]["question_no"]}", name: "template[questions][#{q[0]}][question_no]" %>
        <%= text_field_tag :question, nil, value: "#{q[1]["question_name"]}", name: "template[questions][#{q[0]}][question_name]" %>
        <%= text_field_tag :question_type, nil, value: "#{q[1]["question_type"]}", name: "template[questions][#{q[0]}][question_type]" %>
      </div>
    <% end %>
  <% else %>
    <%= f.fields_for :questions do |q| %>
      <div class="clone_div">
        <div class="field">
          <%= q.text_field :question_no, name: "template[questions][1][question_no]" %>
          <%= q.text_field :question, name: "template[questions][1][question_name]" %>
          <%= q.text_field :question_type, name: "template[questions][1][question_type]" %>
        </div>
      </div>
      <%= link_to 'Add More', '#', class: 'clone_more' %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
var fieldHTML = '';
$(document).ready(function(){
  fieldHTML = $('.clone_div').html();
})
$('.clone_more').click(function(){
    if ($('.selected_criteriums select').length < 5){
      originl_view = fieldHTML;
      index = $('.clone_div .field').size()
      fieldHTML = fieldHTML.replace('name="template[questions][1][question_no]"', 'name="template[questions][' + (index+1) + '][question_no]"');
      fieldHTML = fieldHTML.replace('name="template[questions][1][question_name]"', 'name="template[questions][' + (index+1) + '][question_name]"');
      fieldHTML = fieldHTML.replace('name="template[questions][1][question_type]"', 'name="template[questions][' + (index+1) + '][question_type]"');
      $('.clone_div').append(fieldHTML);
      fieldHTML = originl_view;
    }
    else{
      window.scrollTo(0,300);
      $('.clone_div').parent().find('.errors-full-messages').remove()
      if ($('.clone_div').parent().find('.errors-full-messages').length < 1) {
        $('.clone_div').parent().prepend('<div class="errors-full-messages"> A maximum of 5 criterion can be added.</div>')
      }
    }
  });
</script>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is active</th>
      <th>Questions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.is_active %></td>
        <td><%= template.questions %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @template.is_active %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @template.questions %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>